#pragma once
const char index_html[] PROGMEM = "<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<title>Forza Telemetry</title>\n"
"<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n"
"<link href=\"https://fonts.googleapis.com/css2?family=Chakra+Petch:wght@400;600;700&family=JetBrains+Mono:wght@400;600;700&display=swap\" rel=\"stylesheet\">\n"
"<style>\n"
":root {\n"
"  --bg:       #05080f;\n"
"  --surface:  #0b1220;\n"
"  --surface2: #0f1830;\n"
"  --border:   #162035;\n"
"  --border2:  #1e2d45;\n"
"  --text:     #c8d8f0;\n"
"  --muted:    #3a5070;\n"
"  --teal:     #00f5d4;\n"
"  --pink:     #f72585;\n"
"  --amber:    #ffa500;\n"
"  --white:    #ffffff;\n"
"  --green:    #39ff14;\n"
"  --blue:     #4da6ff;\n"
"  --font-hud: 'Chakra Petch', sans-serif;\n"
"  --font-mono: 'JetBrains Mono', monospace;\n"
"}\n"
"\n"
"*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }\n"
"\n"
"html, body { width: 100%; height: 100%; }\n"
"\n"
"body {\n"
"  background: var(--bg); color: var(--text); font-family: var(--font-hud);\n"
"  display: flex; align-items: center; justify-content: center;\n"
"  overflow: hidden; user-select: none; touch-action: none;\n"
"}\n"
"\n"
".dash {\n"
"  width: 1280px; height: 720px; flex-shrink: 0;\n"
"  display: grid; grid-template-columns: 240px 1fr 230px;\n"
"  grid-template-rows: 45px 1fr 1fr minmax(0, 1.2fr);\n"
"  grid-template-areas:\n"
"    \"rpm-bar  rpm-bar  rpm-bar\"\n"
"    \"gear     speed    tires\"\n"
"    \"stats    gball    pedals\"\n"
"    \"charts   charts   charts\";\n"
"  gap: 12px; transform-origin: center center;\n"
"}\n"
"\n"
".pnl { background: var(--surface); border: 1px solid var(--border); border-radius: 8px; position: relative; overflow: hidden; }\n"
".pnl::before { content: ''; position: absolute; inset: 0; background: repeating-linear-gradient(0deg, transparent, transparent 3px, rgba(255,255,255,0.012) 3px, rgba(255,255,255,0.012) 4px); pointer-events: none; z-index: 0; }\n"
".lbl { font-size: 9px; color: var(--muted); text-transform: uppercase; letter-spacing: 2.5px; font-weight: 600; font-family: var(--font-hud); }\n"
"\n"
".rpm-bar { grid-area: rpm-bar; display: flex; align-items: center; gap: 2px; padding: 6px 10px; }\n"
"#rpm-readout { font-family: var(--font-mono); font-size: 14px; font-weight: 700; color: var(--muted); min-width: 72px; text-align: right; letter-spacing: 1px; transition: color 0.1s; white-space: nowrap; padding-right: 4px; font-variant-numeric: tabular-nums; }\n"
".led { flex: 1; height: 22px; border-radius: 3px; background: #0c1525; border: 1px solid #0f1e35; transition: background 60ms linear, box-shadow 60ms linear; }\n"
"\n"
".gear-pnl { grid-area: gear; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 6px; }\n"
"#val-gear { font-size: clamp(70px, 11vh, 110px); font-weight: 700; font-family: var(--font-hud); line-height: 0.95; color: var(--white); transition: color 0.08s, text-shadow 0.08s; z-index: 1; }\n"
"\n"
".speed-pnl { grid-area: speed; display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 2px; }\n"
"#val-speed { font-size: clamp(90px, 16vh, 160px); font-weight: 700; font-family: var(--font-hud); line-height: 0.9; color: var(--white); font-variant-numeric: tabular-nums; z-index: 1; }\n"
".speed-unit { font-size: 11px; color: var(--muted); letter-spacing: 4px; text-transform: uppercase; z-index: 1; }\n"
".speed-pnl::after { content: ''; position: absolute; width: 55%; height: 70%; background: radial-gradient(ellipse, rgba(0,245,212,0.04) 0%, transparent 70%); pointer-events: none; }\n"
"\n"
".tires-pnl { grid-area: tires; display: grid; grid-template-rows: 18px 1fr 1fr; gap: 6px; padding: 10px; }\n"
".tires-title { text-align: center; z-index: 1; }\n"
".tire-row { display: grid; grid-template-columns: 1fr 1fr; gap: 6px; }\n"
".tire { border-radius: 6px; display: flex; flex-direction: column; align-items: center; justify-content: center; border: 1px solid rgba(255,255,255,0.06); transition: background-color 200ms ease, color 200ms ease; gap: 2px; z-index: 1; }\n"
".tire-t { font-family: var(--font-mono); font-size: 15px; font-weight: 700; font-variant-numeric: tabular-nums; }\n"
".tire-s { font-family: var(--font-mono); font-size: 10px; font-weight: 400; opacity: 0.6; }\n"
"\n"
".stats-pnl { grid-area: stats; padding: 12px 14px; display: flex; flex-direction: column; justify-content: space-evenly; gap: 4px; }\n"
".stat { display: flex; flex-direction: column; gap: 2px; z-index: 1; }\n"
".stat-inner { display: flex; justify-content: space-between; align-items: baseline; }\n"
".stat-v { font-family: var(--font-mono); font-size: 20px; font-weight: 700; font-variant-numeric: tabular-nums; }\n"
".stat-u { font-size: 9px; color: var(--muted); letter-spacing: 1px; margin-left: 3px; }\n"
"\n"
".steer-wrap { z-index: 1; }\n"
".steer-track { position: relative; height: 3px; background: #0c1525; border-radius: 2px; border: 1px solid var(--border2); margin-top: 5px; }\n"
".steer-ctr { position: absolute; top: -5px; left: 50%; transform: translateX(-50%); width: 1px; height: 13px; background: var(--border2); }\n"
".steer-dot { position: absolute; top: -5px; left: 50%; width: 13px; height: 13px; border-radius: 50%; background: var(--white); transform: translateX(-50%); will-change: transform; }\n"
"\n"
".gball-pnl { grid-area: gball; display: flex; flex-direction: column; align-items: center; padding: 8px 10px 6px; gap: 4px; }\n"
".gball-layout { display: flex; width: 100%; flex: 1; min-height: 0; gap: 12px; align-items: center; justify-content: center; }\n"
".susp-col { display: flex; flex-direction: column; gap: 8px; width: 8px; height: 90%; z-index: 1; }\n"
".susp-track { flex: 1; width: 100%; background: #07101f; border-radius: 4px; border: 1px solid var(--border2); position: relative; overflow: hidden; display: flex; flex-direction: column-reverse; }\n"
".susp-fill { width: 100%; height: 100%; background: var(--muted); border-radius: 3px; transform-origin: bottom; transform: scaleY(0); will-change: transform; }\n"
"#cvs-gball { flex: 1; min-height: 0; min-width: 0; width: 100%; height: 100%; z-index: 1; display: block; }\n"
".gball-vals { display: flex; justify-content: space-between; width: 100%; font-family: var(--font-mono); font-size: 11px; font-weight: 600; z-index: 1; }\n"
"\n"
".pedals-pnl { grid-area: pedals; padding: 10px 8px; display: flex; gap: 5px; align-items: stretch; }\n"
".ped-col { flex: 1; display: flex; flex-direction: column; align-items: center; gap: 4px; }\n"
".ped-track { flex: 1; width: 100%; background: #07101f; border-radius: 5px; border: 1px solid var(--border2); position: relative; overflow: hidden; display: flex; flex-direction: column-reverse; }\n"
".ped-fill { width: 100%; height: 100%; border-radius: 3px; transform-origin: bottom; transform: scaleY(0); will-change: transform; }\n"
".ped-pct { font-family: var(--font-mono); font-size: 10px; font-weight: 600; color: var(--muted); font-variant-numeric: tabular-nums; z-index: 1; }\n"
"\n"
".charts-pnl { grid-area: charts; padding: 8px; display: flex; gap: 6px; min-height: 0; }\n"
".chart-col { flex: 1; min-height: 0; position: relative; background: #07101f; border-radius: 6px; border: 1px solid var(--border); overflow: hidden; }\n"
".chart-lbl { position: absolute; top: 4px; left: 7px; z-index: 2; font-family: var(--font-mono); font-size: 9px; font-weight: 600; pointer-events: none; display: flex; gap: 8px; align-items: center; }\n"
".chart-lbl span { display: flex; align-items: center; gap: 3px; }\n"
"canvas.cvs { display: block; width: 100%; height: 100%; }\n"
"\n"
"#ws-status { position: fixed; bottom: 10px; right: 14px; font-family: var(--font-mono); font-size: 10px; letter-spacing: 1px; color: var(--muted); z-index: 100; display: flex; align-items: center; gap: 5px; }\n"
"#ws-dot { width: 6px; height: 6px; border-radius: 50%; background: var(--muted); transition: background 0.3s; }\n"
"#ws-dot.live { background: var(--teal); box-shadow: 0 0 6px var(--teal); }\n"
"#ws-dot.dead { background: var(--pink); }\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<div class=\"dash\">\n"
"  <div class=\"pnl rpm-bar\" id=\"rpm-bar\"><span id=\"rpm-readout\">0 RPM</span></div>\n"
"  <div class=\"pnl gear-pnl\"><div class=\"lbl\">Gear</div><div id=\"val-gear\">-</div></div>\n"
"  <div class=\"pnl speed-pnl\"><div id=\"val-speed\">0</div><div class=\"speed-unit\">km / h</div></div>\n"
"  <div class=\"pnl tires-pnl\">\n"
"    <div class=\"lbl tires-title\">Tire Temp · Slip</div>\n"
"    <div class=\"tire-row\"><div class=\"tire\" id=\"t-fl\"><span class=\"tire-t\">0°</span><span class=\"tire-s\">0.00</span></div><div class=\"tire\" id=\"t-fr\"><span class=\"tire-t\">0°</span><span class=\"tire-s\">0.00</span></div></div>\n"
"    <div class=\"tire-row\"><div class=\"tire\" id=\"t-rl\"><span class=\"tire-t\">0°</span><span class=\"tire-s\">0.00</span></div><div class=\"tire\" id=\"t-rr\"><span class=\"tire-t\">0°</span><span class=\"tire-s\">0.00</span></div></div>\n"
"  </div>\n"
"  <div class=\"pnl stats-pnl\">\n"
"    <div class=\"stat\"><div class=\"lbl\">Power</div><div class=\"stat-inner\"><span class=\"stat-v\" id=\"val-hp\" style=\"color:var(--teal)\">0</span><span class=\"stat-u\">HP</span></div></div>\n"
"    <div class=\"stat\"><div class=\"lbl\">Torque</div><div class=\"stat-inner\"><span class=\"stat-v\" id=\"val-tq\" style=\"color:var(--amber)\">0</span><span class=\"stat-u\">Nm</span></div></div>\n"
"    <div class=\"stat\"><div class=\"lbl\">Boost</div><div class=\"stat-inner\"><span class=\"stat-v\" id=\"val-boost\" style=\"color:var(--blue)\">0.00</span><span class=\"stat-u\">bar</span></div></div>\n"
"    <div class=\"stat steer-wrap\"><div class=\"lbl\">Steer</div><div class=\"steer-track\"><div class=\"steer-ctr\"></div><div class=\"steer-dot\" id=\"steer-dot\"></div></div></div>\n"
"  </div>\n"
"  <div class=\"pnl gball-pnl\">\n"
"    <div class=\"lbl\">G-Force & Susp</div>\n"
"    <div class=\"gball-layout\">\n"
"      <div class=\"susp-col\"><div class=\"susp-track\" title=\"FL Susp\"><div class=\"susp-fill\" id=\"s-fl\"></div></div><div class=\"susp-track\" title=\"RL Susp\"><div class=\"susp-fill\" id=\"s-rl\"></div></div></div>\n"
"      <canvas id=\"cvs-gball\"></canvas>\n"
"      <div class=\"susp-col\"><div class=\"susp-track\" title=\"FR Susp\"><div class=\"susp-fill\" id=\"s-fr\"></div></div><div class=\"susp-track\" title=\"RR Susp\"><div class=\"susp-fill\" id=\"s-rr\"></div></div></div>\n"
"    </div>\n"
"    <div class=\"gball-vals\"><span style=\"color:var(--amber)\">LAT <span id=\"val-glat\">0.00</span>g</span><span style=\"color:var(--teal)\">LON <span id=\"val-glon\">0.00</span>g</span></div>\n"
"  </div>\n"
"  <div class=\"pnl pedals-pnl\">\n"
"    <div class=\"ped-col\"><div class=\"lbl\" style=\"font-size:8px\">THR</div><div class=\"ped-track\"><div class=\"ped-fill\" id=\"p-thr\" style=\"background:linear-gradient(to top,#39ff14,#00c853)\"></div></div><div class=\"ped-pct\" id=\"pv-thr\">0%</div></div>\n"
"    <div class=\"ped-col\"><div class=\"lbl\" style=\"font-size:8px\">BRK</div><div class=\"ped-track\"><div class=\"ped-fill\" id=\"p-brk\" style=\"background:linear-gradient(to top,#f72585,#ff6090)\"></div></div><div class=\"ped-pct\" id=\"pv-brk\">0%</div></div>\n"
"    <div class=\"ped-col\"><div class=\"lbl\" style=\"font-size:8px\">CLU</div><div class=\"ped-track\"><div class=\"ped-fill\" id=\"p-clu\" style=\"background:linear-gradient(to top,#4da6ff,#82c1ff)\"></div></div><div class=\"ped-pct\" id=\"pv-clu\">0%</div></div>\n"
"    <div class=\"ped-col\"><div class=\"lbl\" style=\"font-size:8px\">EBK</div><div class=\"ped-track\"><div class=\"ped-fill\" id=\"p-ebk\" style=\"background:linear-gradient(to top,#ffa500,#ffd060)\"></div></div><div class=\"ped-pct\" id=\"pv-ebk\">0%</div></div>\n"
"  </div>\n"
"  <div class=\"pnl charts-pnl\">\n"
"    <div class=\"chart-col\"><div class=\"chart-lbl\"><div style=\"display:flex;gap:8px;\"><span style=\"color:#00f5d4\">■ HP</span><span style=\"color:#ffa500\">■ TQ</span></div><span class=\"max-val\" id=\"max-pwr\" style=\"margin-left:auto;color:var(--muted)\">0</span></div><canvas class=\"cvs\" id=\"cvs-pwr\"></canvas></div>\n"
"    <div class=\"chart-col\"><div class=\"chart-lbl\"><span style=\"color:#39ff14\">■ RPM</span><span class=\"max-val\" id=\"max-rpm\" style=\"margin-left:auto;color:var(--muted)\">0</span></div><canvas class=\"cvs\" id=\"cvs-rpm\"></canvas></div>\n"
"    <div class=\"chart-col\"><div class=\"chart-lbl\"><span style=\"color:#ffffff\">■ Speed</span><span class=\"max-val\" id=\"max-spd\" style=\"margin-left:auto;color:var(--muted)\">0</span></div><canvas class=\"cvs\" id=\"cvs-spd\"></canvas></div>\n"
"    <div class=\"chart-col\"><div class=\"chart-lbl\"><div style=\"display:flex;gap:8px;\"><span style=\"color:#4da6ff\">■FL</span><span style=\"color:#00d4e8\">■FR</span><span style=\"color:#f72585\">■RL</span><span style=\"color:#ffa500\">■RR</span></div><span class=\"max-val\" id=\"max-slp\" style=\"margin-left:auto;color:var(--muted)\">1.5</span></div><canvas class=\"cvs\" id=\"cvs-slp\"></canvas></div>\n"
"  </div>\n"
"</div>\n"
"<div id=\"ws-status\"><div id=\"ws-dot\"></div><span id=\"ws-txt\">CONNECTING</span></div>\n"
"\n"
"<script>\n"
"const MAX_RPM   = 10000;\n"
"const MAX_POWER = 1200;\n"
"const MAX_SPEED = 500;\n"
"const MAX_SLIP  = 2.0;\n"
"const MAX_G     = 2.0;\n"
"const LED_COUNT = 28;\n"
"\n"
"const rpmBarEl = document.getElementById('rpm-bar');\n"
"const rpmReadout = document.getElementById('rpm-readout');\n"
"const leds = [];\n"
"for (let i = 0; i < LED_COUNT; i++) {\n"
"  const d = document.createElement('div'); d.className = 'led'; rpmBarEl.appendChild(d); leds.push(d);\n"
"}\n"
"\n"
"let lastLit = -1;\n"
"function updateLEDs(rpm) {\n"
"  const maxR = charts.rpm.max && charts.rpm.max > 0 ? charts.rpm.max : 10000;\n"
"  const ratio = Math.min(1, rpm / (maxR * 0.97));\n"
"  const lit = Math.round(ratio * LED_COUNT);\n"
"\n"
"  const rpmStr = parseInt(rpm).toLocaleString() + ' RPM';\n"
"  if (rpmReadout.textContent !== rpmStr) {\n"
"    rpmReadout.textContent = rpmStr;\n"
"    rpmReadout.style.color = ratio > 0.9 ? '#f72585' : (ratio > 0.75 ? '#ffd600' : '#3a5070');\n"
"  }\n"
"\n"
"  if (lit === lastLit) return;\n"
"  lastLit = lit;\n"
"\n"
"  for (let i = 0; i < LED_COUNT; i++) {\n"
"    if (i < lit) {\n"
"      let c, s; const r = i / LED_COUNT;\n"
"      if (r < 0.6)      { c = '#39ff14'; s = `0 0 7px #39ff1480`; }\n"
"      else if (r < 0.8) { c = '#ffd600'; s = `0 0 7px #ffd60080`; }\n"
"      else              { c = '#f72585'; s = `0 0 8px #f7258580`; }\n"
"      leds[i].style.background = c; leds[i].style.boxShadow  = s;\n"
"    } else {\n"
"      leds[i].style.background  = '#0c1525'; leds[i].style.boxShadow   = 'none';\n"
"    }\n"
"  }\n"
"}\n"
"\n"
"function tireColor(c) {\n"
"  if (c < 45)  return ['#0a1f3d', '#4da6ff'];\n"
"  if (c < 75)  return [lerp('#0a1f3d','#0a3020', (c-45)/30), '#7ecfff'];\n"
"  if (c < 95)  return [lerp('#0a3020','#1a3800', (c-75)/20), '#39ff14'];\n"
"  if (c < 115) return [lerp('#1a3800','#3d1a00', (c-95)/20), '#ffd600'];\n"
"  if (c < 135) return [lerp('#3d1a00','#4a0000', (c-115)/20), '#ff6030'];\n"
"  return ['#3a0000', '#f72585'];\n"
"}\n"
"\n"
"function lerp(a, b, t) {\n"
"  const ah = parseInt(a.slice(1),16), bh = parseInt(b.slice(1),16);\n"
"  const ar=ah>>16, ag=(ah>>8)&0xff, ab=ah&0xff;\n"
"  const br=bh>>16, bg=(bh>>8)&0xff, bb=bh&0xff;\n"
"  const r=Math.round(ar+(br-ar)*t), g=Math.round(ag+(bg-ag)*t), bl=Math.round(ab+(bb-ab)*t);\n"
"  return '#'+((r<<16)|(g<<8)|bl).toString(16).padStart(6,'0');\n"
"}\n"
"\n"
"const charts = {\n"
"  pwr: { el: document.getElementById('cvs-pwr'), ctx: null, prev: [null, null], max: 500, lbl: document.getElementById('max-pwr') },\n"
"  rpm: { el: document.getElementById('cvs-rpm'), ctx: null, prev: [null], max: 5000, lbl: document.getElementById('max-rpm') },\n"
"  spd: { el: document.getElementById('cvs-spd'), ctx: null, prev: [null], max: 200, lbl: document.getElementById('max-spd') },\n"
"  slp: { el: document.getElementById('cvs-slp'), ctx: null, prev: [null,null,null,null], max: 1.5, lbl: document.getElementById('max-slp') },\n"
"};\n"
"\n"
"for (const k in charts) { charts[k].ctx = charts[k].el.getContext('2d', { willReadFrequently: true }); }\n"
"\n"
"function resizeCharts() {\n"
"  const dash = document.querySelector('.dash');\n"
"  const vw = document.documentElement.clientWidth;\n"
"  const vh = document.documentElement.clientHeight;\n"
"  const scale = Math.min(vw / 1300, vh / 740);\n"
"  dash.style.transform = `scale(${scale})`;\n"
"\n"
"  for (const k in charts) {\n"
"    const c = charts[k];\n"
"    const wrap = c.el.parentElement;\n"
"    const w = wrap.clientWidth, h = wrap.clientHeight;\n"
"    if (w > 0 && h > 0 && (c.el.width !== w || c.el.height !== h)) { c.el.width = w; c.el.height = h; c.prev = c.prev.map(() => null); }\n"
"  }\n"
"  const gb = document.getElementById('cvs-gball');\n"
"  const gw = gb.clientWidth, gh = gb.clientHeight;\n"
"  if (gw > 0 && gh > 0 && (gb.width !== gw || gb.height !== gh)) { gb.width = gw; gb.height = gh; }\n"
"}\n"
"\n"
"function scrollPush(c, vals, colors) {\n"
"  const { ctx, el, prev } = c; const w = el.width, h = el.height;\n"
"  if (!w || !h) return;\n"
"\n"
"  const localMax = Math.max(...vals);\n"
"  if (!c.max) c.max = 10;\n"
"  if (localMax * 1.15 > c.max) { c.max = localMax * 1.15; } else { c.max = c.max * 0.999 + Math.max(localMax, 0.01) * 0.001; }\n"
"  if (c.max < 10 && c.el.id !== 'cvs-slp') c.max = 10;\n"
"  if (c.max < 1.0 && c.el.id === 'cvs-slp') c.max = 1.0; \n"
"  if (c.lbl) c.lbl.textContent = c.max >= 100 ? Math.round(c.max) : c.max.toFixed(1);\n"
"\n"
"  const imgData = ctx.getImageData(1, 0, w - 1, h);\n"
"  ctx.putImageData(imgData, 0, 0); ctx.clearRect(w - 1, 0, 1, h);\n"
"\n"
"  for (let i = 0; i < vals.length; i++) {\n"
"    const newY = h - Math.max(0, Math.min(1, vals[i] / c.max)) * h;\n"
"    const pY = prev[i] ?? newY; const minY = Math.min(pY, newY); const segH = Math.max(1, Math.abs(pY - newY) + 1);\n"
"    ctx.fillStyle = colors[i]; ctx.fillRect(w - 1, minY, 1, segH); c.prev[i] = newY;\n"
"  }\n"
"}\n"
"\n"
"const gTrail = []; const TRAIL = 55;\n"
"\n"
"function drawGBall(lat, lon) {\n"
"  const cv = document.getElementById('cvs-gball');\n"
"  const cx2 = cv.getContext('2d');\n"
"  const w = cv.width, h = cv.height;\n"
"  if (!w || !h) return;\n"
"  const cx = w/2, cy = h/2, r = Math.min(cx, cy) - 10;\n"
"\n"
"  cx2.clearRect(0,0,w,h);\n"
"  cx2.save(); cx2.beginPath(); cx2.arc(cx, cy, r, 0, Math.PI*2); cx2.clip();\n"
"  cx2.fillStyle = 'rgba(0,245,212,0.04)'; cx2.fillRect(cx,0,r,h);\n"
"  cx2.fillStyle = 'rgba(247,37,133,0.04)'; cx2.fillRect(0,0,cx,h);\n"
"  cx2.restore();\n"
"\n"
"  cx2.lineWidth = 1;\n"
"  const ringFontSz = Math.max(8, r * 0.10);\n"
"  cx2.font = `${ringFontSz}px JetBrains Mono, monospace`; cx2.textAlign = 'center';\n"
"  [0.5, 1.0, 1.5, 2.0].forEach(g => {\n"
"    const rf = g / MAX_G;\n"
"    cx2.strokeStyle = g === 1.0 ? 'rgba(255,255,255,0.22)' : 'rgba(255,255,255,0.08)';\n"
"    cx2.beginPath(); cx2.arc(cx, cy, r * rf, 0, Math.PI * 2); cx2.stroke();\n"
"    cx2.fillStyle = 'rgba(255,255,255,0.22)'; cx2.fillText(g.toFixed(1) + 'g', cx, cy - r * rf + ringFontSz);\n"
"  });\n"
"  cx2.strokeStyle = 'rgba(255,255,255,0.09)';\n"
"  cx2.beginPath(); cx2.moveTo(cx, cy - r); cx2.lineTo(cx, cy + r); cx2.stroke();\n"
"  cx2.beginPath(); cx2.moveTo(cx - r, cy); cx2.lineTo(cx + r, cy); cx2.stroke();\n"
"\n"
"  if (gTrail.length > 1) {\n"
"    cx2.beginPath();\n"
"    gTrail.forEach((p, i) => {\n"
"      const x = cx + (p.lat/MAX_G)*r, y = cy - (p.lon/MAX_G)*r;\n"
"      i === 0 ? cx2.moveTo(x,y) : cx2.lineTo(x,y);\n"
"    });\n"
"    cx2.strokeStyle = 'rgba(255,166,0,0.55)'; cx2.lineWidth = 2; cx2.stroke();\n"
"  }\n"
"\n"
"  const px = cx + (lat/MAX_G)*r, py = cy - (lon/MAX_G)*r;\n"
"  cx2.beginPath(); cx2.arc(px, py, 14, 0, Math.PI*2); cx2.fillStyle = 'rgba(255, 165, 0, 0.2)'; cx2.fill();\n"
"  cx2.beginPath(); cx2.arc(px,py,5,0,Math.PI*2); cx2.fillStyle = '#ffa500'; cx2.fill();\n"
"}\n"
"\n"
"const $ = id => document.getElementById(id);\n"
"const dom = {\n"
"  gear: $('val-gear'), speed: $('val-speed'), hp: $('val-hp'), tq: $('val-tq'), boost: $('val-boost'), glat: $('val-glat'), glon: $('val-glon'),\n"
"  steer: $('steer-dot'), sFL: $('s-fl'), sFR: $('s-fr'), sRL: $('s-rl'), sRR: $('s-rr'),\n"
"  pThr: $('p-thr'), pvThr: $('pv-thr'), pBrk: $('p-brk'), pvBrk: $('pv-brk'), pClu: $('p-clu'), pvClu: $('pv-clu'), pEbk: $('p-ebk'), pvEbk: $('pv-ebk'),\n"
"  tires: { fl:$('t-fl'), fr:$('t-fr'), rl:$('t-rl'), rr:$('t-rr') }, wsDot: $('ws-dot'), wsTxt: $('ws-txt'),\n"
"};\n"
"\n"
"let lastMsgTime = 0, latest = null, lastReset = 0;\n"
"\n"
"function resetDash() {\n"
"  dom.gear.textContent = \"-\"; dom.gear.style.color = '#ffffff'; dom.gear.style.textShadow = 'none';\n"
"  dom.speed.textContent = \"0\"; dom.hp.textContent = \"0\"; dom.tq.textContent = \"0\"; dom.boost.textContent = \"0.00\"; dom.glat.textContent = \"0.00\"; dom.glon.textContent = \"0.00\";\n"
"  dom.steer.style.left = \"50%\";\n"
"  dom.pThr.style.height = '0%'; dom.pvThr.textContent = '0%'; dom.pBrk.style.height = '0%'; dom.pvBrk.textContent = '0%';\n"
"  dom.pClu.style.height = '0%'; dom.pvClu.textContent = '0%'; dom.pEbk.style.height = '0%'; dom.pvEbk.textContent = '0%';\n"
"  if(dom.sFL) { dom.sFL.style.transform='scaleY(0)'; dom.sFR.style.transform='scaleY(0)'; dom.sRL.style.transform='scaleY(0)'; dom.sRR.style.transform='scaleY(0)'; }\n"
"  updateLEDs(0);\n"
"}\n"
"\n"
"function t(el, val) { if (el.textContent != val) el.textContent = val; }\n"
"\n"
"function render() {\n"
"  const now = Date.now();\n"
"  if (latest) {\n"
"    lastMsgTime = now; const d = latest; latest = null;\n"
"    t(dom.gear, d.gear); t(dom.speed, d.speed.toFixed(1)); t(dom.hp, d.hp); t(dom.tq, d.torque); t(dom.boost, d.boost.toFixed(2)); t(dom.glat, d.glat.toFixed(2)); t(dom.glon, d.glon.toFixed(2));\n"
"\n"
"    const maxR = charts.rpm.max && charts.rpm.max > 0 ? charts.rpm.max : 10000;\n"
"    const rpmRatio = d.rpm / maxR;\n"
"    if (rpmRatio > 0.92) { dom.gear.style.color = '#f72585'; dom.gear.style.textShadow = '0 0 30px #f7258580'; }\n"
"    else if (rpmRatio > 0.8) { dom.gear.style.color = '#ffd600'; dom.gear.style.textShadow = '0 0 20px #ffd60050'; }\n"
"    else { dom.gear.style.color = '#ffffff'; dom.gear.style.textShadow = 'none'; }\n"
"\n"
"    updateLEDs(d.rpm); dom.steer.style.transform = `translateX(-50%) translateX(${d.steer}px)`;\n"
"    dom.pThr.style.transform = `scaleY(${d.accel/100})`; t(dom.pvThr, d.accel  + '%');\n"
"    dom.pBrk.style.transform = `scaleY(${d.brake/100})`; t(dom.pvBrk, d.brake  + '%');\n"
"    dom.pClu.style.transform = `scaleY(${d.clutch/100})`; t(dom.pvClu, d.clutch + '%');\n"
"    dom.pEbk.style.transform = `scaleY(${d.ebrake/100})`; t(dom.pvEbk, d.ebrake + '%');\n"
"\n"
"    if (d.susp && dom.sFL) {\n"
"      dom.sFL.style.transform = `scaleY(${d.susp.fl})`; dom.sFR.style.transform = `scaleY(${d.susp.fr})`;\n"
"      dom.sRL.style.transform = `scaleY(${d.susp.rl})`; dom.sRR.style.transform = `scaleY(${d.susp.rr})`;\n"
"    }\n"
"\n"
"    for (const k of ['fl','fr','rl','rr']) {\n"
"      const td = d.tires[k]; const [bg, fg] = tireColor(td.t); const el = dom.tires[k];\n"
"      el.style.backgroundColor = bg; el.style.color = fg;\n"
"      t(el.querySelector('.tire-t'), td.t + '°C'); t(el.querySelector('.tire-s'), td.s.toFixed(2));\n"
"    }\n"
"\n"
"    gTrail.push({ lat: d.glat, lon: d.glon }); if (gTrail.length > TRAIL) gTrail.shift(); drawGBall(d.glat, d.glon);\n"
"    scrollPush(charts.pwr, [Math.max(0, d.hp), Math.max(0, d.torque)], ['#00f5d4', '#ffa500']);\n"
"    scrollPush(charts.rpm, [d.rpm], ['#39ff14']); scrollPush(charts.spd, [d.speed], ['#ffffff']);\n"
"    scrollPush(charts.slp, [d.tires.fl.s, d.tires.fr.s, d.tires.rl.s, d.tires.rr.s], ['#4da6ff','#00d4e8','#f72585','#ffa500']);\n"
"\n"
"  } else if (now - lastMsgTime > 250 && now - lastReset > 100) {\n"
"    resetDash(); gTrail.length = 0; drawGBall(0, 0);\n"
"    scrollPush(charts.pwr, [0, 0], ['#00f5d4', '#ffa500']); scrollPush(charts.rpm, [0], ['#39ff14']);\n"
"    scrollPush(charts.spd, [0], ['#ffffff']); scrollPush(charts.slp, [0, 0, 0, 0], ['#4da6ff','#00d4e8','#f72585','#ffa500']);\n"
"    lastReset = now;\n"
"  }\n"
"  requestAnimationFrame(render);\n"
"}\n"
"\n"
"function connect() {\n"
"  const host = window.location.hostname || 'localhost';\n"
"  const wsUrl = `ws://${host}/ws`;\n"
"  console.log('Connecting to', wsUrl);\n"
"  let ws = new WebSocket(wsUrl);\n"
"  \n"
"  ws.onopen = () => { \n"
"    dom.wsDot.className = 'live'; \n"
"    dom.wsTxt.textContent = 'LIVE'; \n"
"  };\n"
"  \n"
"  ws.onmessage = e => { \n"
"    try {\n"
"      latest = JSON.parse(e.data); \n"
"    } catch(err) {\n"
"      console.error('Invalid telemetry data', err);\n"
"    }\n"
"  };\n"
"  \n"
"  ws.onclose = () => { \n"
"    dom.wsDot.className = 'dead'; \n"
"    dom.wsTxt.textContent = 'RECONNECTING...'; \n"
"    setTimeout(connect, 2000); \n"
"  };\n"
"  \n"
"  ws.onerror = (err) => {\n"
"    console.error('WebSocket Error', err);\n"
"    ws.close();\n"
"  };\n"
"}\n"
"\n"
"let resizeTimer;\n"
"window.addEventListener('resize', () => { clearTimeout(resizeTimer); resizeTimer = setTimeout(resizeCharts, 80); });\n"
"setTimeout(resizeCharts, 120);\n"
"connect(); requestAnimationFrame(render);\n"
"</script>\n"
"</body>\n"
"</html>";
